build_script:
  - ghc Main.hs -O2
  - "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin\\gcc.exe" compiler.c -o transpiler.exe -O3
#

before_build:
  - choco install ghc
  - refreshenv
  - ghci --version
#

artifacts:
  - path: Main.exe
    name: Main
  - path: transpiler.exe
    name: transpiler
#
